### ISSUE TITLE
Should the AVCaptureSession be started asynchronously?

### ISSUE THREAD

**Issue by shagedorn** [mikebuss/MTBBarcodeScanner#101]
Given the existance of a `didStartScanningBlock`, I assumed calling `startScanningWithResultBlock:error:` would perform all expensive tasks asynchronously, but this doesn't seem to be the case. I believe these two blocks of code execute in the exact same way:

```
[self.activityIndicator startAnimating];

[self.scanner startScanningWithResultBlock:^(NSArray *codes) {
    // process the results here 
    } error:nil];

[self.activityIndicator stopAnimating];
```

vs.

```
[self.activityIndicator startAnimating];

self.scanner.didStartScanningBlock = ^() {
    [self.activityIndicator stopAnimating];
};

[self.scanner startScanningWithResultBlock:^(NSArray *codes) {
    // process the results here 
    } error:nil];
```

I've also confirmed in Xcode's CPU profiler that the main thread is blocking for a bit, while all other thread are idle:

![scanner](https://cloud.githubusercontent.com/assets/462183/22779820/928e2382-eebc-11e6-9026-16cc28199a4d.png)

I assume the reason is [`[self.session startRunning]`](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L268), and the [docs](https://developer.apple.com/reference/avfoundation/avcapturesession/1388185-startrunning?language=objc) are pretty clear about it:

> **Important:**
> The startRunning method is a blocking call which can take some time, therefore you should perform session setup on a serial queue so that the main queue isn't blocked (which keeps the UI responsive). 

The problem is that this issue cannot be fixed on the client side because `startScanningWithResultBlock:error:` also touches views that must be used on the main thread. I would propose an internal serial queue, and every line that modifies the session must dispatch to that queue first. The `didStartScanningBlock` must then be dispatched back to main. I'd be willing to give this a try in a PR, but feel free to suggest other solutions.

Surprisingly enough, `UIActivityIndicatorView` (which my example is based on, and we also use it within our app) handles the blocking main thread really well and keeps spinning, so it's not a super obvious issue. If however you attempt to tap a button (e.g., "Cancel") while the camera is loading, you will notice a delay.

**Comment by mikebuss** [comment]
I like the proposed solution of moving the session setup to a background thread. If you have a PR for this, I'd be happy to merge it in. Thanks for finding the issue!

**Comment by shagedorn** [comment]
Will start working on this next week.

**Comment by lisacmer** [comment]
I believe those changes can break thread safety, as for now self.session object is accessed from different threads (for example [self.session removeInput:deviceInput]; still called on main thread).
For example according to https://developer.apple.com/library/content/samplecode/AVCam/Listings/Objective_C_AVCam_AVCamCameraViewController_m.html
once initialised in main thread all calls to session must be perform on sessionQueue.

**Comment by mikebuss** [comment]
Good catch. @shagedorn is this something you could take a look at? If not, I can take a look sometime this week.

**Comment by shagedorn** [comment]
I can take a look in the upcoming days, but cannot promise a date at the moment.

**Comment by mikebuss** [comment]
Ok thanks, that's no problem. If you find you can't get to it, just let me know and I'll dive in.

**Comment by shagedorn** [comment]
I don't really have the time to fix/improve this this week (if this needs fixing, which I'm not entirely convinced of), but some thoughts:

* I initially planned to dispatch every session access to the private queue, but this is problematic during setup. After the session has been created, there's some code that needs to run on `main`, mostly [`self.capturePreviewLayer = [AVCaptureVideoPreviewLayer layerWithSession:newSession]`](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L503). So we'd need to switch back and forth between the private and main queue, which has the potential of tricky errors.

* Afaik, it is not generally a problem to access `AVCaptureSession` on different threads, as `AVFoundation` is thread safe. The sample code mentions that it's not safe to mutate the session's outputs/inputs/connections from multiple threads at the same time, which is not something we're doing.

* The pragmatic tradeoff we chose was to configure the session on `main` and only dispatch (all!) calls to `startRunning`/`stopRunning`. This should ensure their call order does not get mixed up (since we always use the same serial queue). The `.session` property is always set from `main` and acts as a guard whether we have a current session or not. It may be possible that an older session still hangs around, but [`.session` is `nil`](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L335-L336) (which means starting/creating a new one is [allowed](https://github.com/mikebuss/MTBBarcodeScanner/blob/develop/Classes/ios/Scanners/MTBBarcodeScanner.m#L259)).

So I'm not sure if we actually have a potential problem here.

**Comment by mikebuss** [comment]
Thanks for taking a look @shagedorn. I can't seem to find anything in Apple's documentation that says our implementation could cause issues, since (like you said), we're not modifying the session's properties from multiple threads at the same time.

@lisacmer if you can point us towards documentation saying what we're doing is finicky, let us know. Otherwise, I think the current implementation fits within the documentation I've seen.

I'm also running this change in a production app with crash reporting, so if I see any incidents I'll definitely swing back and take a look. Please let me know if you see any crashes on your end as well.

**Comment by shagedorn** [comment]
We're also shipping this to production very soon, and it's been through a lot of internal testing already. Will create issues/provide fixes should we see any oddities.

**Comment by lisacmer** [comment]
I don't think Apple's documentation clear enough about this topic. Should starting or stopping an `AVCaptureSession` be considered as 'mutating'? What will happen if i'll try to `removeDeviceInput` while starting a session (switching camera right after start)? I'm just saying that since all accessing in Apple's example takes place on a single thread (except for creation), this question would be unimportant.

Also current project documentation is unclear (maybe i could not find it) about next topics:
- Am i able to call `startScanningWithResultBlock` before previous call returned completion block
- Am i able to call `startScanningWithResultBlock` after previous sessions returned completion block, but `stopSession` was not called.
- Am i able to make calls to other methods (`setCamera`) before completion block returns.

We came to investigating this project after having random hangs during rapid switch between starting and stopping the session (even in an example project). I believe it has to do something with accessing an `AVCaptureSession` from different threads. 

Apart from that i think it's not a very good idea to access nonatomic property 
`@property (nonatomic, strong) AVCaptureSession *session;`
from different threads:
calling setter inside `startScanningWithResultBlock` 
`    self.session = session;`
on a main thread
while calling getter inside `freezeCapture` 
`        [self.session stopRunning];`
on a sessionThread. Again i understand that probability of corruption is very low, but i think in that case `session` property should be `atomic`.

**Comment by mikebuss** [comment]
Here are answers to your questions. I'll work towards getting these added to the documentation, but some feel like odd flow (for example, I'm not sure why someone would try to start scanning after you've already started?)

> Am i able to call startScanningWithResultBlock before previous call returned completion block didStartScanning

> Am i able to call startScanningWithResultBlock after previous sessions returned completion block didStartScanning, but stopSession was not called.

> Am i able to make calls to other methods (setCamera) before completion block didStartScanning returns.

No, each of these would return an NSError. You can only have one running session at a time, and you must first start the session before configuring it.

For the random hangs you've been experiencing, are you able to reproduce them in the sample project included in this repo? If you have steps to reproduce, I can take a look and narrow this down.

For the `atomic` vs `nonatomic` discussion: this brings me back to your question of `Should starting or stopping an AVCaptureSession be considered as 'mutating'?`, and I think the answer is: Apple doesn't really say. Because of that, it's unclear to me if this will be a problem. If there's even a 0.01% chance this will crash on someone, I want to fix it, but I'd like to make sure we're not adding complexity when we don't have to.

I'm going to investigate this more over the weekend, but please let me know if you're able to reproduce an issue (and the steps necessary) with the current implementation so I can take a look.

**Comment by shagedorn** [comment]
Re: atomic vs. nonatomic:

Since the session property is accessed from two different queues, you can probably construct a theoretic example where the session queue tries to read the session property, while the nonatomic setter on main has already been called, but not all instructions have finished internally, leading to a potentially corrupt session when accessing it. For that, I wouldn't mind changing it to `atomic` – it doesn't create any effort, won't have noticeable drawbacks, and is probably the right thing – I also wouldn't expect this to solve an real problems though.

I don't believe such a scenario would actually ever happen in this library because the session is not exposed in the header, and only a few defined paths in our code modify the session. I don't think you can really trigger such a race condition using the current public scanner API.

Could it be that the experienced hangs have to do with the call order after starting a session, similar to what we fixed in https://github.com/mikebuss/MTBBarcodeScanner/commit/7570dfe4cd876ba497bc92f77b88424b20ae3c0c?
