### ISSUE TITLE
Swift example not working

### ISSUE THREAD

**Issue by ledikari** [mikebuss/MTBBarcodeScanner#117]
error message: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempted to start scanning on a device with no camera. Check requestCameraPermissionWithSuccess: method before calling startScanningWithResultBlock:

**Comment by mikebuss** [comment]
What device are you using to test your code? Does the app have permission to access the camera according to the Settings app?

Please share the code, or a snippet if you can.

**Comment by mikebuss** [comment]
It looks like the error was descriptive here: the library could not see a camera on the device because the user did not grant permission in the Settings app. As the error suggests, you'll need to use `requestCameraPermissionWithSuccess` to ask for permission before accessing the camera. Here is an example of that:

```
MTBBarcodeScanner.requestCameraPermission(success: { success in
    if success {
        do {
            try self.scanner?.startScanning(resultBlock: { codes in
                if let codes = codes {
                    for code in codes {
                        let stringValue = code.stringValue!
                        print("Found code: \(stringValue)")
                    }
                }
            })
        } catch {
            NSLog("Unable to start scanning")
        }
    } else {
        UIAlertView(title: "Scanning Unavailable", message: "This app does not have permission to access the camera", delegate: nil, cancelButtonTitle: nil, otherButtonTitles: "Ok").show()
    }
})
```

I've [added this](https://github.com/mikebuss/MTBBarcodeScanner/commit/32fac3e0fc66a3a4f719b4fae0851b95c383a124) to the Swift example to help anyone else with the same issue. The example existed in Objective-C, but was not added to the more recent Swift one. Hope this helps!

**Comment by ledikari** [comment]
thanks! it works now.
