### ISSUE TITLE
'AVCaptureStillImageOutput' is deprecated

### ISSUE THREAD

**Issue by Premal-Khetani** [mikebuss/MTBBarcodeScanner#122]
Hello, This is best lib ever. 

I am using it since last year. Now i am going to integrate it in new project. This project's targeted os is ios 10 and i am getting this error 

> /MTBBarcodeScanner.m:122:31: 'AVCaptureStillImageOutput' is deprecated: first deprecated in iOS 10.0 - Use AVCapturePhotoOutput instead

Please let me know what to do?. 

Thank you :)

**Comment by mikebuss** [comment]
It looks like the `AVCaptureStillImageOutput` method was deprecated in iOS 10. You can still continue to use MTBBarcodeScanner in the meantime. I'll look into implementing the new `AVCapturePhotoOutput` so this warning goes away in the next version of MTBBarcodeScanner.

Thanks for letting me know!

**Comment by mikebuss** [comment]
These warnings are now fixed in https://github.com/mikebuss/MTBBarcodeScanner/commit/23127f71b54cd3856c2d6ce13274bfaa1b077ba2, https://github.com/mikebuss/MTBBarcodeScanner/commit/ae0f06410e113f7edebf81c5c7bc4358a9bec2e1 and https://github.com/mikebuss/MTBBarcodeScanner/commit/488c2a9686053bbbafe730d513cdde8bae00587c on the `develop` branch.

If anyone has an iOS 8 or 9 device and wants to volunteer some time testing this doesn't break backwards compatibility, that would be much appreciated. I'm going to hold off on releasing these changes to give people time to test with the `develop` branch. If I don't hear of any issues, I'll release this as version 5.0.2 some time next week.

Thank you!

**Comment by Premal-Khetani** [comment]
@mikebuss Thank you So much :)

**Comment by bluelabeldeveloper1** [comment]
@mikebuss  Warning is disappeared. I checked it with scanning working fine just need to know that when you will release this version?
