### ISSUE TITLE
Implement CaptureStillImage

### ISSUE THREAD

**Issue by frozts91** [mikebuss/MTBBarcodeScanner#127]
Hi @mikebuss i want to implement function captureStillImage on Swift 3, in the doc you said implement after start scanning, how to do that?

```
try self.scanner?.startScanning(resultBlock: { codes in
    self.scanner?.freezeCapture()
     self.scanner?.captureStillImage({ (UIImage?, Error?) in
                            code
                        })
```

is that correct? because its return nil

**Comment by mikebuss** [comment]
I wasn't aware of this limitation so I didn't document it, but the session must be running in order to capture a still image. So, calling `freezeCapture` before `captureStillImage` won't work - you'll have to capture the still image and then freeze.

I have tried this and it works, but let me know if you run in to any issues:

```swift
self.scanner?.captureStillImage({ (image, error) in
    NSLog("The image and/or error are accessible here");
})
self.scanner?.freezeCapture()
```
