### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by hugobgranja** [mikebuss/MTBBarcodeScanner#133]
The video quality shown on the MTBBarcodeScanner view is of much lower quality than the one shown on the camera app. Any way to solve this?
Device: iPad Air 2

**Comment by mikebuss** [comment]
This library sets the quality to "high" (`AVCaptureSessionPresetHigh`) when it initializes the capture session. At the moment, there's no way to configure that, because it was chosen as a compromise between battery life and ability to scan codes.

To get higher quality, you have a few options: if you'd like, you could submit a pull request making the `sessionPreset` configurable in MTBBarcodeScanner. I don't have the time to do this (at least at the moment), but I would accept a pull request for it. The full list of quality options is here - there are only a few that are higher than "high", but they go up to 4k:
https://developer.apple.com/documentation/avfoundation/avcapturesession.preset

Alternatively, you could drop down a level and implement your scanning with AVFoundation, ditching MTBarcodeScanner altogether. That would give you 100% flexibility, but take away some of the convenience of MTBBarcodeScanner.

I'll put this on my list of features to add. If this ticket gets enough reactions or comments, I'll consider adding this functionality when I have time. Thanks!
