### ISSUE TITLE
Not detecting barcodes when in flipped camera mode

### ISSUE THREAD

**Issue by mattwritescode** [mikebuss/MTBBarcodeScanner#138]
I suspect this is because when you use the front facing camera, everything is a mirror image so the barcodes are reversed. Not sure if there's a real fix for this, but if not, there's no reason to have the flip button in the example.

**Comment by mikebuss** [comment]
What type of barcode are you scanning? The library is able to scan QR codes from the front camera without any issues, for example. Older phones with worse front cameras don't work as well, but modern ones do.

Regardless, since MTBBarcodeScanner is built on top of Apple's AVFoundation, this is not something we can control or improve. So, I'm going to close this. I would recommend filing a radar with Apple if you feel a particular type of code should be scannable from the front camera. I would include an example for them to test with as well. Thank you!

**Comment by mattwritescode** [comment]
Right on. Sounds like it’s out of scope for the library. I’m trying to scan
code 128.
