### ISSUE TITLE
Catalyst Support?

### ISSUE THREAD

**Issue by MikeMilzz** [mikebuss/MTBBarcodeScanner#152]
I've been using and very much appreciating this project for a while. This weekend I installed Catalina and the XCode beta. I was excited to compile my iPad app and see how much work I'll need to do to have a Mac app. After clearing a deprecation issue, I found a few issues in the MTBBarcodeScanner.m file that I'm not surprised exist. 

My question is if there are plans to support Catalyst and to make this library compatible with running on MacOS. If there are plans, then I'll happily do some testing. If there isn't, I completely understand and am not sure how big of an ask this might be. I'm willing to dig in and see what I can figure out if that would help the project move forward. 

If there's a better way to communicate other than the issue tracker, please let me know. 

Thanks.

**Comment by mikebuss** [comment]
Thanks Mike. I'd like to rewrite MTBBarcodeScanner in Swift and take advantage of all the new tools, including Catalyst, so that's on the horizon.

I haven't decided how I'm going to handle the existing Objective-C code, and whether the library needs to support iOS versions as old as iOS 8 (as it currently does). I may put the existing code on a separate branch for people who need it, and rewrite the main branch in Swift to take advantage of the latest Apple goodies.

If anyone has an opinion on the future of MTBBarcodeScanner and how the legacy code base should be handled, please feel free to comment here. I will also update this ticket with the progress. I think it's likely I'll have a Swift rewrite in the next month or so.

**Comment by MikeMilzz** [comment]
That's great news Mike. I think a new branch the supports more modern versions is totally appropriate as the current version is very stable and shouldn't need updates for people sticking with older versions of iOS for whatever reason. 

I went through and ifdef'd out a few errors that had to do with camera stability and now I (hopefully) only have this one error to work through. I'll update this post when I find an appropriate option for UIKit for macOS. 

NSData *data = [AVCapturePhotoOutput JPEGPhotoDataRepresentationForJPEGSampleBuffer:photoSampleBuffer previewPhotoSampleBuffer:previewPhotoSampleBuffer];

**Comment by MikeMilzz** [comment]
Turns out I just needed to scroll up a few lines and read your very useful comment 
// This method uses methods that are deprecated in iOS 10. We also implement the updated method (captureOutput:didFinishProcessingPhoto:error:), so we can ignore the warning here.

I commented out this whole method and was able to get my app to build and run. My view with the scanner didn't pop-up but at least it compiles now.

**Comment by mikebuss** [comment]
@MikeMilzz Glad to hear it compiles. I haven’t been able to tackle Catalyst support yet, and unfortunately it’s pretty low on my priority list. If anyone wants to submit support in the form of a pull request, I can review and merge it in. Otherwise, this feature may not get added.
