### ISSUE TITLE
Problem to read some codes

### ISSUE THREAD

**Issue by hdoria** [mikebuss/MTBBarcodeScanner#16]
MTBBarcodeScanner is awesome and works fine for some barcodes. However, I'm having trouble reading some barcodes from Brazilian banks. I can read these codes using other libraries. I'm using the MTBBarcodeScanner sample project to read the following codes:

![screenshot 2015-01-20 09 10 01](https://cloud.githubusercontent.com/assets/73786/5816911/b037d7d0-a084-11e4-8994-5b1603a3139e.png)

![screenshot 2015-01-20 09 10 12](https://cloud.githubusercontent.com/assets/73786/5816913/b03b686e-a084-11e4-81ee-e73e94923ab8.png)

![screenshot 2015-01-20 09 10 23](https://cloud.githubusercontent.com/assets/73786/5816914/b03c5a76-a084-11e4-888f-eba8f97f0fa6.png)

![screenshot 2015-01-20 09 10 57](https://cloud.githubusercontent.com/assets/73786/5816912/b03861aa-a084-11e4-87e5-5dee55c3d5af.png)

![screenshot 2015-01-20 09 11 18](https://cloud.githubusercontent.com/assets/73786/5816915/b03e38e6-a084-11e4-9294-c98fb49abd6a.png)

**Comment by mikebuss** [comment]
Sorry to hear you're having issues.

I'm thinking that since ITF and ITF14 codes were just [added](https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVMetadataMachineReadableCodeObject_Class/index.html#//apple_ref/doc/constant_group/Machine_Readable_Object_Types) to AVFoundation in iOS 8 that there are still some bugs with scanning them. It looks like [some people](http://technology.ezeenow.com/posts/12604/iOS_8_camera_does_not_recognize_data_matrix_code) are having issues scanning Data Matrix codes, which were also added in iOS 8. Other libraries like ZBar and ZXing might be able to read these codes because they don't rely on the Apple-built AVFoundation framework.

I'm going to file a radar with Apple to see if they can fix this issue. If I hear back from Apple I'll report the progress back here.

If you want to help, or if anyone else sees this ticket and is still experiencing the issue, I would recommend [filing a radar](https://bugreport.apple.com/) with Apple that you're seeing this issue.

**Comment by mikebuss** [comment]
Going to close this for now. If I hear more from Apple I'll report back!
