### ISSUE TITLE
Interface Orientation Issue

### ISSUE THREAD

**Issue by reinholdB** [mikebuss/MTBBarcodeScanner#44]
I have an old app which is not using auto layout. I would like to have a preview view covering the whole screen. It works fine on iPhones, but it doesn't work on an iPad after changing the rotation once (initially the whole screen is covered). 

If I don't pass the preview view to MTBBarscodeScanner's initializer the view always covers the whole screen.

![screen shot 2015-09-18 at 16 33 03](https://cloud.githubusercontent.com/assets/883363/9961935/7aa06bc0-5e23-11e5-9a14-23da92dc8279.png)

**Comment by reinholdB** [comment]
actually the view is rotating correctly, but AVCaptureVideoPreviewLayer isn't

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention @reinholdB. I just released version 1.8.2, which exposes a `previewLayer` property pointing at the layer responsible for drawing the camera input. Can you try adjusting this manually when you detect a device rotation?

If there's anything else I can add that would help, please let me know.

**Comment by reinholdB** [comment]
Thanks Mike for the quick reaction. 

This definitely helps but it's not enough to expose a CALayer because I need to access layer.connection.videoOrientation (reference: http://stackoverflow.com/a/30394124/512130)

**Comment by mikebuss** [comment]
Sorry @reinholdB I may have misunderstood your original comment. The video orientation is automatically rotated by MTBBarcodeScanner whether the view is using auto layout or struts and sprints, so that shouldn't be an issue. Note that when I say rotated, I mean everything the camera sees as upright will always appear upright on the screen - if the view was originally 300x600, it will still be 300x600, but the camera input will appear correctly.

You mentioned "I would like to have a preview view covering the whole screen", which you should be able to achieve by manually adjusting the `previewLayer` property frame. If you're seeing that the video itself is upside down on the screen, you might have to set a breakpoint in `refreshVideoOrientation` inside MTBBarcodeScanner and make sure it's setting it correctly.

If you have a demo project you could share, that would help as well. If not, please let me know how I can be of more help!
