### ISSUE TITLE
iOS 9

### ISSUE THREAD

**Issue by mojtabacazi** [mikebuss/MTBBarcodeScanner#49]
Nothing happens after calling  `startScanningWithResultBlock:` on iOS9.

**Comment by mikebuss** [comment]
MTBBarcodeScanner has been tested on iOS 9 on iPhone and iPad. Please try using the demo project, as it's guaranteed to be setup correctly. If you are experiencing issues in your project, please provide a zip file or code I can help with.

![img_3447](https://cloud.githubusercontent.com/assets/1574304/10180091/664702e8-66d8-11e5-95f1-9df7d8e3c342.PNG)

**Comment by youandme12399** [comment]
Hi mikebuss!
When i run startScan, app crash.
This is info bug :
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Scanning is prohibited on this device.              Check requestCameraPermissionWithSuccess: method before calling startScanningWithResultBlock:'
*** First throw call stack:
(0x25ab786b 0x371b6dff 0x25ab7741 0x268472ab 0x7263d 0x196761 0x1963f9 0x29bc969b 0x29be12f9 0x29d71245 0x29c82cc3 0x29c829cd 0x29c82947 0x29bc56ab 0x2949167d 0x2948cd79 0x2948cc09 0x2948c129 0x2948bdeb 0x294855bf 0x25a7a0f1 0x25a783e7 0x25a78825 0x259cb1e9 0x259cafdd 0x2ec6faf9 0x29c3017d 0xdfe09 0x378e1873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mikebuss** [comment]
Hi @youandme12399 - this error is saving you need to check the `requestCameraPermissionWithSuccess:` method before calling `startScanningWithResultBlock:`. It appears your device has not given permission to your app to access the camera. You can change this in the Settings app.

**Comment by youandme12399** [comment]
thanks for support :)

**Comment by ShashankThakur** [comment]
Library scans perfectly on iphone but on ipad it is not able to scan after trying for minutes..

**Comment by mikebuss** [comment]
@ShashankThakur can you try using the demo project supplied with the library? Also, can you report back which iPad you are using, and what iOS version?
