### ISSUE TITLE
FIX for highResolutionStillImageOutputEnabled not supported in iOS 7

### ISSUE THREAD

**Issue by kiwox** [mikebuss/MTBBarcodeScanner#60]
I'm using MTBarcode for a Swift project that requires support for iOS 7. There is just one line that should be added to keep working on it.

MTBarcodeScanner.m line 356
```
if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8) {
    self.stillImageOutput.highResolutionStillImageOutputEnabled = YES;
}
```

I've replaced them to enable support for iOS 7, but every time I update my CocoaPods or setup in another computer I should make this change manually. Can you please add this change to master branch?

**Comment by mikebuss** [comment]
Thanks for bringing this to my attention. What version of the pod are you using? If you're on 1.8.10, you should have [this fix](https://github.com/mikebuss/MTBBarcodeScanner/blob/master/Classes/ios/Scanners/MTBBarcodeScanner.m#L357-L359), which adds a check for compatibility:

```objective-c
if ([self.stillImageOutput respondsToSelector:@selector(isHighResolutionStillImageOutputEnabled)]) {
    self.stillImageOutput.highResolutionStillImageOutputEnabled = YES;
}
```

After some investigating, it looks like this wasn't merged into `develop`, but was merged into `master` and deployed as 1.8.10. (I've since merged this into `develop` to fix that issue).

As a sanity check, I've deployed a version 1.8.11 that `master` and `develop` now point at. Can you check if that fixes your issue and let me know? I opted for the `respondsToSelector` check instead of the iOS version, but they should both accomplish the same thing.
