### ISSUE TITLE
Can not get MTBTorchModeAuto to work in B4i

### ISSUE THREAD

**Issue by JackKirk** [mikebuss/MTBBarcodeScanner#64]
Hi,

I am using your code via the iBarcode library wrapper in the AnyWhereSoftware B4i product.

For reference you may like to view:

[]https://www.b4x.com/index.html
[]https://www.b4x.com/android/forum/threads/ibarcode-library.47354/

This wrapper has recently been enhanced to incorporate the MTBTorchModeOff/ MTBTorchModeOn/ MTBTorchModeAuto features, see this thread:

[]https://www.b4x.com/android/forum/threads/equivalent-of-b4a-phone-phonesensors-type_light.62181/#post-396928

Everything works brilliantly except for one thing - when MTBTorchModeAuto is used the torch never turns on, even in total darkness.

I'd be appreciative of any help/ suggestions/ fixes you may be able to conjure up.

**Comment by mikebuss** [comment]
Hey @JackKirk - awesome library! I'm going to bookmark this if I ever work on Android development.

To answer your question: the torch functionality in MTBBarcodeScanner is a little limited. The scanner object gives you the ability to turn the torch on or off, but doesn't allow you to automatically turn the torch on based on lighting conditions. The reason there's a `MTBTorchModeAuto` option is because this is a wrapper over `AVCaptureTorchMode`, which has the following options:

```objective-c
/*!
 @enum AVCaptureTorchMode
 @abstract
    Constants indicating the mode of the torch on the receiver's device, if it has one.

 @constant AVCaptureTorchModeOff
    Indicates that the torch should always be off.
 @constant AVCaptureTorchModeOn
    Indicates that the torch should always be on.
 @constant AVCaptureTorchModeAuto
    Indicates that the torch should be used automatically depending on ambient light conditions.
*/
typedef NS_ENUM(NSInteger, AVCaptureTorchMode) {
	AVCaptureTorchModeOff  = 0,
	AVCaptureTorchModeOn   = 1,
	AVCaptureTorchModeAuto = 2,
} NS_AVAILABLE(10_7, 4_0) __TVOS_PROHIBITED;
```

If you'd like to accomplish turning the torch on/off depending on lighting conditions, I would suggest taking a look at [this post](http://stackoverflow.com/a/28298472/1816745), which talks about continuously sampling the brightness level.

I'm going to close this for now, as it's more of a feature request than a bug, but if you'd like to discuss this further please feel free to [email me](mailto:mike@mikebuss.com).
