### ISSUE TITLE
AVCaptureSession Stop Running

### ISSUE THREAD

**Issue by hardikdevios** [mikebuss/MTBBarcodeScanner#66]
**First of all, Thanks for the Lib**
I have few questions like **AVCaptureSession Interruption**.

Some time Session being stop after few seconds and was unable to detect the error, i have  put the Debug points in this lib but nothing fire and camera stops scanning, So after little bit more research i have found one thing that some notifications will be called like 

```
- AVCaptureSessionRuntimeErrorNotification
- AVCaptureSessionInterruptionEndedNotification
- AVCaptureSessionWasInterruptedNotification
```

And after adding this Observers in my controller i came up with this error in my Log

```
NSConcreteNotification 0x13f1dc0f0 {name = AVCaptureSessionRuntimeErrorNotification; object = <AVCaptureSession: 0x13f506680 [AVCaptureSessionPresetHigh]>
	<AVCaptureDeviceInput: 0x13dfc4ae0 [Back Camera]> -> <AVCaptureStillImageOutput: 0x13f360c50>
	<AVCaptureDeviceInput: 0x13dfc4ae0 [Back Camera]> -> <AVCaptureVideoPreviewLayer: 0x13f182030>
	<AVCaptureDeviceInput: 0x13dfc4ae0 [Back Camera]> -> <AVCaptureMetadataOutput: 0x13f35c610>; userInfo = {
    AVCaptureSessionErrorKey = "Error Domain=AVFoundationErrorDomain Code=-11800 \"The operation could not be completed\" UserInfo={NSUnderlyingError=0x13f1de2f0 {Error Domain=NSOSStatusErrorDomain Code=-16811 \"(null)\"}, NSLocalizedFailureReason=An unknown error occurred (-16811), NSLocalizedDescription=The operation could not be completed}";
}}
```

_So My question is_
1. Why AVSession keeps stoping automatically?
2. Can we handle this in better way using this lib?

> 
To reproduce this issue in your demo you can just go to basic example and Click start scanning and wait for some minutes or use it for some minutes.this method will fire and session will stop scanning.Thanks

**Comment by mikebuss** [comment]
I wasn't able to reproduce this on an iPhone 6 Plus running iOS 9. I turned the capture on and waited 20 minutes but didn't see any issues. Since this is not something specific to MTBBarcodeScanner, and sounds more like an AVFoundation issue, I think your best bet is to use StackOverflow or file a bug report to Apple.

**Comment by zackfletch00** [comment]
+1, I'm having the same issue on my iPhone 6S Plus running iOS 9.3.  On a seemingly random basis, sometimes as frequently as every 15-20 seconds, my session is interrupted or stopped (sometimes i get WasInterrupted notification, other times I get DidStopRunning notification.  The torch also cuts off during these times.  My best workaround was to observe for those notifications and call startRunning on the session and relight the torch manually each time that an interruption occurs.

**This might occur more often while playing music in the background**, because I noticed few interruptions without music playing, and frequent interruptions with music.

**Comment by zackfletch00** [comment]
Amazingly, the interruptions seem to be related to **Headphones** being plugged in!  Unplug headphones, and no interruptions.  Plug them back in, and the session is once again stopping itself.  Problem solved?

**Comment by zscgeek** [comment]
Were you ever able to track down a fix to this other then removing the headphones?

**Comment by davidmaitland** [comment]
Would love to know this as well. I had to write some hacky code to detect whether the session has crashed and restart it.

**Comment by mikebuss** [comment]
I haven't had much luck reproducing this on my end with an iPhone 6S Plus running iOS 9.3.2. Is anyone able to reproduce this reliably with a set of steps? 

I created a bare-bones implementation using AVFoundation in a separate Xcode project we can use. Hopefully this will help narrow it down a bit. If you're able to reproduce the issue in this project, please let me know, and I can investigate further (and move any fixes into MTBBarcodeScanner):
https://www.dropbox.com/s/us8eoz5bxtjxacy/SampleBarcodeProject.zip?dl=0

If this turns out to be an issue with AVFoundation, we can submit this project (and steps to reproduce) as a radar to Apple.

**Comment by hardikdevios** [comment]
This is more likely an issue from Apple side because the session is getting stop without no reason, i have write code with my own and same thing is happening. And yes session is getting frequent interruption while you plugin the headphones or playing music in background even if you have started camera and put it in background that also be case.
