### ISSUE TITLE
Type of code

### ISSUE THREAD

**Issue by Jkurbs** [mikebuss/MTBBarcodeScanner#74]
Just one last question! How do I know what type of code I just read? Because if it's a Url (Qr Code) I want to do something and if it's another type I want to do another action. I'm using swift. Thank you very much.

**Comment by mikebuss** [comment]
@Jkurbs because this is a general programming question, please ask it on [StackOverflow](http://stackoverflow.com). GitHub issues are only for reporting issues with this project.

To get you started, here is an example for using the project in Swift:
https://github.com/mikebuss/MTBBarcodeScanner/issues/18#issuecomment-80762411

The codes are reported as strings. You can perform conditional logic based on those strings.
