### ISSUE TITLE
Does freeze capture stop the scanner?

### ISSUE THREAD

**Issue by shekbagg** [mikebuss/MTBBarcodeScanner#75]
When I `freezeCapture()` on a successful scan, sometimes it scans the same barcode a second time and the callback gets called again. So, is freeze capture a safe way to stop capturing and then use unfreeze when ready to restart? Or should I always use stopScanning()?

**Comment by mikebuss** [comment]
I believe you're seeing the code a second time because AVFoundation returns codes as quickly as it can process them in the image stream (and often times this means the same code multiple times). These codes get queued up, and will get reported back through the `resultBlock`.

`freezeCapture()` doesn't set the `resultBlock` to nil, so codes can still be reported if they were queued up. Calling `stopScanning()` will work, as the `resultBlock` is set to nil, but tearing down the session requires a little bit of time and _might_ report a duplicate code before it finishes.

If your project needs to scan exactly one code and stop receiving more, you could add a boolean that stops processing received codes after the first one. If that's not an option, you could set the `resultBlock` of the `MTBBarcodeScanner` object manually to `nil`, so no codes will be reported back. You'll just have to remember to give it a valid block if you want to receive codes afterwards.

Hope this helps. I'm going to close this for now, but feel free to comment or shoot me an [email](mailto:mike@mikebuss.com).

**Comment by shekbagg** [comment]
Thanks!
