### ISSUE TITLE
Crash on iOS 8.4  - mach-o, but wrong architecture 

### ISSUE THREAD

**Issue by CarlinhaCamargo** [mikebuss/MTBBarcodeScanner#94]
I've run into a crash when testing on an Iphone 5c iOS 8.4. 
Log error shows: "MTBBarcodeScanner.framework/MTBBarcodeScanner: mach-o, but wrong architecture"

Installed MTBBarcodeScanner with carthage. 
App suport: 8.0 

is there a version that I can use and this doesn't happen?

**Comment by mikebuss** [comment]
I need more information to help debug this. Does the error happen every time you run the app?

It sounds like this may be an issue with how MTBBarcodeScanner was installed using Carthage. Can you try some of the suggestions from [this search](https://www.google.com/search?q=mach-o%2C+but+wrong+architecture+carthage&oq=mach-o%2C+but+wrong+architecture+carthage&gs_l=serp.3..33i21k1j33i160k1.33577.34639.0.34679.9.8.0.0.0.0.127.596.4j2.6.0....0...1c.1.64.serp..3.5.506...0j35i39k1j0i22i30k1.W8iuoHgqZ_I)?

Because this is not specific to MTBBarcodeScanner, I am going to close this.
